/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Audio: typeof import('./src/components/PlayBar/Audio.vue')['default']
    Bar: typeof import('./src/components/PlayBar/Bar.vue')['default']
    Btns: typeof import('./src/components/Btns/index.vue')['default']
    Card: typeof import('./src/components/Card/index.vue')['default']
    Comment: typeof import('./src/components/Comment/index.vue')['default']
    ControlPlay: typeof import('./src/components/PlayBar/ControlPlay.vue')['default']
    DownLoadSide: typeof import('./src/components/DownLoadSide/index.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    Emj: typeof import('./src/components/Emj/index.vue')['default']
    Pic: typeof import('./src/components/Pic/index.vue')['default']
    PlayBar: typeof import('./src/components/PlayBar/index.vue')['default']
    PlayList: typeof import('./src/components/PlayBar/PlayList.vue')['default']
    Progress: typeof import('./src/components/Progress/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VolControl: typeof import('./src/components/PlayBar/VolControl.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
